{
 "title": "LENDING API",
 "tags": [
  "lending",
  "api",
  "springboot"
 ],
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": "label_values(jvm_memory_used_bytes, application)"
   },
   {
    "name": "instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"lending-api\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\",instance=\"$instance\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "4xx Responses/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",status=~\"4..\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx Responses/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Exceptions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",exception!=\"None\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top Endpoints",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(15,sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\"}[5m])) by (uri,method))"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Request Duration (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\"}[5m])) by (le))"
    }
   ]
  }
 ]
}